### ISSUE TITLE
Link to "Build beautiful data visualizations with D3"

### ISSUE THREAD

**Issue by curran** [datavis-tech/awesome-dataviz-education#10]
https://www.fullstack.io/fullstack-d3

**Comment by arky** [comment]
@curran This content is already present. Recommend closing this as duplicate.

**Comment by curran** [comment]
Agree. Closing.

**Comment by curran** [comment]
Thanks for getting involved @arky ! This is great.

**Comment by arky** [comment]
@curran Pleasure is all mine. It is my way of paying back for all the tutorials and training material you created for the community.
