### ISSUE TITLE
Link to Lynda courses

### ISSUE THREAD

**Issue by curran** [datavis-tech/awesome-dataviz-education#13]
* https://www.lynda.com/D3-js-tutorials/D3-js-Essential-Training-Data-Scientists/504428-2.html 2016
 * https://www.lynda.com/D3-js-tutorials/Learning-Data-Visualization-D3-js/594451-2.html 2017

**Comment by curran** [comment]
Or maybe not... They're so dated.

**Comment by arky** [comment]
+1 Let's not include this content. Recommend closing this bugsas invalid/wontfix.

**Comment by curran** [comment]
Agree. Closing.
