### ISSUE TITLE
Link to "Data Visualization for Storytelling and Discovery"

### ISSUE THREAD

**Issue by curran** [datavis-tech/awesome-dataviz-education#14]
Data Visualization
for Storytelling and Discovery

https://journalismcourses.org/data-viz-course-material.html?source=post_page---------------------------

**Comment by arky** [comment]
Correct Link: https://journalismcourses.org/course/data-visualization-for-storytelling-and-discovery/

Related content: https://journalismcourses.org/course/data-journalism-and-visualization-with-free-tools/
